codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "88...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        branches:
          - master
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error
        only_pulls: false
        paths:
          - "**/src"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

