---
name: Continuous Integration Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.build/**'
      - '.github/workflows/deployment.yml'

jobs:
  build_java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: cescoffier/setup-jdk@v1.1.3
        with:
          java-version: 'openjdk8'
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

  build_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 11
        uses: cescoffier/setup-jdk@v1.1.3
        with:
          java-version: 'openjdk11'
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

  build_java12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 12
        uses: cescoffier/setup-jdk@v1.1.3
        with:
          java-version: 'openjdk12'
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

  build_java14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 14
        uses: cescoffier/setup-jdk@v1.1.3
        with:
          java-version: 'openjdk14'
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

  quality:
    needs: [build_java8, build_java11, build_java12, build_java14]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Coverage and Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
        run: |
          mvn verify -Pcoverage
          mvn sonar:sonar \
            -Dsonar.projectKey=smallrye_smallrye-mutiny \
            -Dsonar.projectName="SmallRye Mutiny" \
            -Dsonar.organization=smallrye \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_LOGIN \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco.xml
