---
name: Pull Request Build

on: pull_request

jobs:
  build_java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: cescoffier/setup-jdk@v1.1.3
        with:
          java-version: 'openjdk8'
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

  build_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 11
        uses: cescoffier/setup-jdk@v1.1.3
        with:
          java-version: 'openjdk11'
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

  build_java12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 12
        uses: cescoffier/setup-jdk@v1.1.3
        with:
          java-version: 'openjdk12'
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

  build_java14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 14
        uses: cescoffier/setup-jdk@v1.1.3
        with:
          java-version: 'openjdk14'
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml


